fix patches

diff --git a/patches/0001-remove-overrides-for-non-technical-users.patch b/patches/0001-remove-overrides-for-non-technical-users.patch
--- a/patches/0001-remove-overrides-for-non-technical-users.patch
+++ b/patches/0001-remove-overrides-for-non-technical-users.patch
@@ -1,12 +1,12 @@
-From 2c569b89c98e3cba73b6e21d3d58cd0aa2c65c93 Mon Sep 17 00:00:00 2001
+From 86bbb2eb1f2c90e1ccd5e993b98d98d288122712 Mon Sep 17 00:00:00 2001
 From: Preston Petrie <preston159@users.noreply.github.com>
 Date: Fri, 9 May 2025 14:31:36 -0500
 Subject: [PATCH 1/7] remove overrides for non-technical users
 
 ---
- system_files/overrides/etc/profile.d/dnf-dummy.sh | 6 ------
- system_files/overrides/usr/bin/dnf                | 9 ---------
- 2 files changed, 15 deletions(-)
+ .../overrides/etc/profile.d/dnf-dummy.sh       |  6 ------
+ system_files/overrides/usr/bin/dnf             | 18 ------------------
+ 2 files changed, 24 deletions(-)
  delete mode 100644 system_files/overrides/etc/profile.d/dnf-dummy.sh
  delete mode 100755 system_files/overrides/usr/bin/dnf
 
@@ -24,19 +24,28 @@ index f2a63318..00000000
 -fi
 diff --git a/system_files/overrides/usr/bin/dnf b/system_files/overrides/usr/bin/dnf
 deleted file mode 100755
-index 33b4b29d..00000000
+index a6aedeb4..00000000
 --- a/system_files/overrides/usr/bin/dnf
 +++ /dev/null
-@@ -1,9 +0,0 @@
+@@ -1,18 +0,0 @@
 -#!/usr/bin/bash
 -
 -# Redirect to dnf5 if we are running inside a container
 -if systemd-detect-virt -cq || { [[ -e /run/.containerenv || -e /.dockerenv ]]; }; then
--    exec dnf5 "$@"
+-    exec /usr/bin/dnf5 "$@"
 -fi
 -
--echo -e "ERROR: Fedora Atomic images utilize rpm-ostree instead (and is discouraged to use).\nPlease, \e]8;;https://docs.bazzite.gg/Installing_and_Managing_Software/\aread our documentation\e]8;;\a\n\e]8;;https://docs.bazzite.gg/Installing_and_Managing_Software/\ahttps://docs.bazzite.gg/Installing_and_Managing_Software/\e]8;;\a\n"
--${SUDO_USER:+sudo -u $SUDO_USER dbus-launch} bash -lc 'xdg-open "https://docs.bazzite.gg/Installing_and_Managing_Software"'
+-# Show the error if we attempt to use the install/uninstall commands
+-for arg in "$@"; do
+-    if [[ $arg == "install" || $arg == "in" || $arg == "remove" || $arg == "rm" ]]; then
+-        echo -e "ERROR: Fedora Atomic images utilize rpm-ostree instead (and is discouraged to use).\nPlease, \e]8;;https://docs.bazzite.gg/Installing_and_Managing_Software/\aread our documentation\e]8;;\a\n\e]8;;https://docs.bazzite.gg/Installing_and_Managing_Software/\ahttps://docs.bazzite.gg/Installing_and_Managing_Software/\e]8;;\a\n" >&2
+-        ${SUDO_USER:+sudo -u $SUDO_USER dbus-launch} bash -lc 'xdg-open "https://docs.bazzite.gg/Installing_and_Managing_Software"'
+-        exit 1
+-    fi
+-done
+-
+-# Fallback to dnf5
+-exec /usr/bin/dnf5 "$@"
 -- 
 2.51.0
 
